version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/SpringHMS-0.0.1-SNAPSHOT.war SpringHMS-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - SpringHMS-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
  base-directory: 'target/SpringHMS-0.0.1-SNAPSHOT.war'