version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/SpringHMS-0.0.1-SNAPSHOT.jar SpringHMS-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - SpringHMS-0.0.1-SNAPSHOT.jar
    - .ebextensions/**/*
  base-directory: 'target/SpringHMS-0.0.1-SNAPSHOT.jar'